<?php

declare(strict_types=1);

namespace Modules\Setup\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Carbon;
use Modules\Setup\Models\OnboardingSession;
use Modules\Setup\Services\OnboardingMetricsService;

/**
 * Chantier 32.10 (deep 14-layer audit, layer 9 — fake/dead classification):
 * `OnboardingMetricsService::generateDailySnapshot()`'s own docblock says
 * "Called by a scheduled command once per day" — confirmed via grep that no
 * such command has ever existed anywhere in this app; `FunnelSnapshot`'s
 * own class docblock makes the identical claim ("Generated by a scheduled
 * command"). A real, working method with zero producer outside its own
 * test — classified "activate", not "delete": the funnel-measurement
 * concept itself is real, already-documented, and used by
 * `OnboardingMetricsController::stats()`'s dashboard (a different,
 * on-the-fly aggregate) — the snapshot table exists specifically to avoid
 * re-scanning raw event tables for historical trend queries, a real,
 * legitimate need once there's more than a few days of data.
 *
 * Same scheduling mechanism already proven for Modules\Analytics
 * ('forecasting:nightly'), Modules\Helpdesk ('helpdesk:check-sla-breaches'),
 * and Modules\Sales ('sales:generate-recurring-orders') — hook
 * `Illuminate\Console\Scheduling\Schedule::class` directly via
 * `callAfterResolving()` in the module's own ServiceProvider, independent
 * of the root Kernel binding.
 */
class GenerateOnboardingFunnelSnapshotsCommand extends Command
{
    protected $signature = 'setup:generate-funnel-snapshots {--date=}';

    protected $description = "Génère l'instantané quotidien de l'entonnoir d'onboarding pour chaque tenant ayant eu de l'activité";

    public function handle(OnboardingMetricsService $service): int
    {
        $date = $this->option('date') ? Carbon::parse((string) $this->option('date')) : Carbon::yesterday();

        $tenantIds = OnboardingSession::query()
            ->whereBetween('started_at', [$date->copy()->startOfDay(), $date->copy()->endOfDay()])
            ->distinct()
            ->pluck('tenant_id');

        foreach ($tenantIds as $tenantId) {
            $service->generateDailySnapshot((int) $tenantId, $date->copy());
        }

        $this->info(count($tenantIds) . " instantané(s) d'entonnoir généré(s) pour le " . $date->toDateString() . '.');

        return self::SUCCESS;
    }
}
