<?php

declare(strict_types=1);

namespace Modules\Setup\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

use Illuminate\Database\Eloquent\Factories\HasFactory;
/**
 * FunnelSnapshot
 *
 * Daily aggregate of onboarding funnel metrics for a tenant.
 * Generated by a scheduled command; one row per tenant per day.
 * Powers the analytics dashboard without scanning raw event tables.
 *
 * @property int        $id
 * @property int        $tenant_id
 * @property Carbon     $snapshot_date
 * @property int        $sessions_started
 * @property int        $sessions_completed
 * @property int        $sessions_abandoned
 * @property int|null   $avg_duration_seconds
 * @property int|null   $median_duration_seconds
 * @property float|null $step1_completion_rate
 * @property float|null $step2_completion_rate
 * @property float|null $step3_completion_rate
 * @property float|null $step4_completion_rate
 * @property float|null $step5_completion_rate
 * @property float|null $ai_mapping_adoption_rate
 * @property Carbon     $created_at
 */
class FunnelSnapshot extends Model
{
    use HasFactory;
    use \Modules\AuditLog\Traits\HasAuditLog;
    protected $table = 'setup_onboarding_funnel_snapshots';

    public $timestamps = false;

    protected $fillable = [
        'tenant_id',
        'snapshot_date',
        'sessions_started',
        'sessions_completed',
        'sessions_abandoned',
        'avg_duration_seconds',
        'median_duration_seconds',
        'step1_completion_rate',
        'step2_completion_rate',
        'step3_completion_rate',
        'step4_completion_rate',
        'step5_completion_rate',
        'ai_mapping_adoption_rate',
    ];

    protected $casts = [
        'snapshot_date'            => 'date',
        'step1_completion_rate'    => 'decimal:2',
        'step2_completion_rate'    => 'decimal:2',
        'step3_completion_rate'    => 'decimal:2',
        'step4_completion_rate'    => 'decimal:2',
        'step5_completion_rate'    => 'decimal:2',
        'ai_mapping_adoption_rate' => 'decimal:2',
        'created_at'               => 'datetime',
    ];

    // -----------------------------------------------------------------------
    // Scopes
    // -----------------------------------------------------------------------

    /** @param Builder<self> $query */
    public function scopeForTenant(Builder $query, int $tenantId): Builder
    {
        return $query->where('tenant_id', $tenantId);
    }
}
